def print_diagram():
    print("+-------------------+")
    print("|    Excellent Developer Qualities    |")
    print("+-------------------+")
    print("+-------------------+")
    print("|     Curiosity     |")
    print("+-------------------+")
    print("| Exploring New Technologies |")
    print("| Learns Continuosly |")
    print("| Asking Questions |")
    print("+-------------------+")
    print()
    print("+-------------------+")
    print("| Attention To Details |")
    print("+-------------------+")
    print("| Writting Clean Code |")
    print("| Tests Thoroughly |")
    print("| Clearly document |")
    print("+-------------------+")
    print()
    print("+-------------------+")
    print("| Problem Solving Mindset |")
    print("+-------------------+")
    print("| Analysing Problems |")
    print("| Breaking Down tasks to subtasks |")
    print("| Finding Optimal Solutions |")
    print("+-------------------+")

print_diagram()